/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl */

#ifndef _Included_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
#define _Included_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    accept
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_accept
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    available
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_available
  (JNIEnv *, jobject);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    bind
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_bind
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_close
  (JNIEnv *, jobject);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    connect
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_connect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    create
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_create
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    getInputStream
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_getInputStream
  (JNIEnv *, jobject);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    getOutputStream
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_getOutputStream
  (JNIEnv *, jobject);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    listen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_listen
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    sendUrgentData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_sendUrgentData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    getOption
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_getOption
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl
 * Method:    setOption
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_leandrosales_jdccp_wrapper_NativeDCCPSocketImpl_setOption
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
